{{- if .Values.uiService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kratos-auth.fullname" . }}-ui-secrets
  labels:
    {{- include "kratos-auth.labels" . | nindent 4 }}
    component: ui
type: Opaque
data:
  session-secret: {{ .Values.uiService.sessionSecret | b64enc | quote }}
{{- end }}
